function [fitresult, gof] = createFit(Velocity_BL_values, Ylocation_BL_values,Title)
%CREATEFIT(VELOCITY_BL_VALUES,YLOCATION_BL_VALUES)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : Velocity_BL_values
%      Y Output: Ylocation_BL_values
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 10-Nov-2018 16:31:32


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( Velocity_BL_values, Ylocation_BL_values );

% Set up fittype and options.
ft = fittype( 'rat44' );
excludedPoints = excludedata( xData, yData, 'Indices', 12 );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.339706962070075 0.817176415224338 0.377547669768167 0.972604932176721 0.605318590650978 0.338236165549055 0.927983722291575 0.898424694301282 0.850706460713442];
opts.Exclude = excludedPoints;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure(1);
h = plot( fitresult, xData, yData, excludedPoints );
% Label axes
xlabel('Velocity in m/s')
ylabel ('Y probe location in mm')
title([Title])
grid minor


